### PR TITLE
Log to file

### PR DESCRIPTION
**Pull request by jdtournier**
This attempts to detect when the output is redirected to file and adjusts the output accordingly. See discussion around issues #161 & #168. 

Are we happy to merge this in...?

### CODE REVIEW

**Comment by Lestropie** [comment]
On Windows I'm getting a leading `<-[0K` on progress bars as they're working, and a residual one on its own line after the progress bar is done before the terminal prompt appears.

In `tckgen` the `<-[0K` overlaps the command name at the start of the line, i.e. it reads:
`<-[0Ken: [ xx%]      xxxxx generated,      xxxxx selected`

**Comment by jdtournier** [comment]
@Lestropie : are you sure that was running with the `log_to_file` branch and the latest commit (ef6d06f)? I can't see any way you'd see that output if that was the case - if it wasn't working you'd see a _trailing_  `<-[0K`...

**Comment by jdtournier** [comment]
OK, I was wrong. I get the same as you...
I'll simplify the windows case to a simple carriage return, and pad out the string with spaces if the `update()` shrinks it...

**Comment by jdtournier** [comment]
OK, see what you make of the latest changes...

**Comment by Lestropie** [comment]
Looks correct to me on both Linux and Windows.

**Pull request merged**
